export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS"
export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER"
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const SET_SHOW_SOLD = "SET_SHOW_SOLD"